name: PublishDocs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.76.5'
        extended: true

    - name: Setup Git
      env: 
        SSH_KEY: ${{secrets.DOC_SITE_SECRET}}
        USERNAME: ${{github.actor}} 
      run: tools/gh-actions/init_git.sh

    - name: Publish
      run: tools/docs.sh -p
